### ISSUE TITLE
Chromium support

### ISSUE THREAD

**Issue by leedoyle** [photodiode/panorama-view#101]
Any plans to land support for Chromium?

**Comment by aude** [comment]
Last I checked, that is impossible, because Chrom{e,ium} does not have any way for extensions to hide tabs. They consider it a security problem.

Firefox solved it by implementing a tab hide API, and a browser interface (as far as I remember) that you can use to manage hidden tabs, so that extensions can't just hide your tabs without you ever knowing.

See https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/hide for more information.

**Comment by leedoyle** [comment]
@aude, still, a way to organize the opened tabs visually and manage them would be great - regardless of whether it is possible to hide the tabs or not.

**Comment by aude** [comment]
To implement parts of this extension for a browser without tab hide API would be really weird, as the core functionality is missing.

Suggestions for you would be to try Firefox, or to look for similar extensions that are refined to work without tab hide API (for example: https://www.makeuseof.com/tag/10-extensions-chrome-tab-management/).

**Comment by leedoyle** [comment]
@ayude, on my hardware firefox is 1.5 times slower, and that's the price I wouldn't like to pay. Chrome's extensions for tab management are mostly terrible, they lack the positive developments of Tab Groups the firefox ecosystem managed to retain.

**Comment by NatoBoram** [comment]
Now that Google is killing ad-blockers in Chromium, would you be more inclined to switch? :)
