### ISSUE TITLE
Since version 0.7.4, every tab thumbnail image is not immediately renewed again.

### ISSUE THREAD

**Issue by GitHubro5** [photodiode/panorama-view#43]
Hi.

**Since version 0.7.4, every tab thumbnail image is not immediately renewed again.**
Thumbnail images aren't updated even though I select the desired tab and then run Panorama View once more.
Likewise, thumbnail images aren't updated even though time has passed.
I found the "Less demanding thumbnail updating" sentence in the version history section.

Is there a reason for this change?
I'm currently using Firefox 59.0.1 (64-bit) and Panorama View 0.7.3 on very old computer, but I have not found any problems yet.

Rather, I think it will be better to add a function that allows the user to set the thumbnail image update interval time manually.
For example, in this way -> (Do Nothing - Slower - Recommended - Faster - Immediately).

**Comment by photodiode** [comment]
I am sorry about that, I have noticed the same myself.
With the way it was done in 0.7.3 there seemed to be a slight lag whenever I switched to the panorama view, which is why I made the change for 0.7.4. But that made thumbnails not always update..
How many tabs to you have open and active?

I have also been experimenting with other ways of doing it including periodic update, but because videos and such seem to stop updating after 10 seconds I don't see much point.
They are updated on tab update anyways.

I changed it back with v0.7.7 for now

**Comment by GitHubro5** [comment]
Thank you.

I am usually opening about 20 tabs and using.
Personally, I have not experienced slight lag yet.
However, if I use Panorama View with extensions.webextensions.tabhide.enabled enabled, the entire Windows OS system will be freezed occasionally.
So I have to force the computer to reboot.
I don't know why, but I know that Firefox's tabhide functionality is still experimental.
So I think it is still unstable.
That freezing occurs in all versions to date.

Also, because there is no auto sizing feature yet, I am using the 270% zoomed Panoarama View page.
If the page gets longer, pressing the mouse wheel button on the thumbnail image to close the tab activates the auto scrolling function.
I think it would be better to disable the auto scrolling function on the thumbnail image when the page gets longer.
