### ISSUE TITLE
What is the difference with Simple Tab Groups?

### ISSUE THREAD

**Issue by gagarine** [photodiode/panorama-view#94]
https://github.com/Drive4ik/simple-tab-groups

Their is some cosmetic difference, but is their any other big differences?

**Comment by projectdelphai** [comment]
probably the biggest difference for me is the design differences. The old tab groups was simple, you saw a grid of all the tabs and you could organize them in any way you want. But simple-tab-groups seems unnecessarily complicated, there's a list view but there's also a grid view? And you have to manually create groups too? It's definitely a polished addon, it just seems like it adds too much complexity when for me, just being able to visually see the grid and move tabs around is the biggest appeal.

Also I found [this thread](https://www.reddit.com/r/firefox/comments/7cq7jk/tab_groups_alternatives/dxais1z/) a while back that says it doesn't store the history, it just stores the URL but that was 4 months ago, so maybe it's changed since then.
