### ISSUE TITLE
Maintaining/Updating Panorama View

### ISSUE THREAD

**Issue by projectdelphai** [photodiode/panorama-view#95]
@photodiode 

I recently found this addon and it's pretty much exactly what I've wanted since the old tab groups was shut down, a simple and easy way to organize tabs. However, it doesn't look like this repo is maintained or updated much anymore.

The biggest issue I had with the addon was not being able to drag and drop tabs to create new groups so I made my own fork [here](https://github.com/projectdelphai/panorama-view) but I don't want to create a new repo or project when this already exists. I plan on bringing in more changes from other issue and pull requests in this repo, so is it possible to transfer ownership or allow me to work on the code if you're not interested in this project anymore? 

Sorry if this is the wrong place to send this message, but I wasn't sure how else to contact you.

**Comment by mikhoul** [comment]
@projectdelphai   I've seen also that this addon seem abandoned and that you intend to take over.

On your fork the issues are not enabled so that's why I reach for you here.

Previosly I was using https://morikko.github.io/synctabgroups/ but it also seem abandoned and in it's current state it is not reliable for daily use.

I have as question for you with your fork would you be willing to generate a version of the extension for Chromium ?   Since most API are now the same it should not be to hard. 

The main difference for this type of extension regarding API is the tab-hiding API that is not available in Chromium. But for me it's nt an issue since browser are fast for me there is no need to keep tab "alive" just in case I would need it later. I prefer to save memory for other purpose. 

If you do it let me know I would be willing to test it and use it.

Best Regards :octocat: 


**Note:** There is a lot of Polyfill/library to make the porting seamless: 

[mozilla/webextension-polyfill](https://github.com/mozilla/webextension-polyfill)
[acvetkov/then-chrome](https://github.com/acvetkov/then-chrome)
[KeithHenry/chromeExtensionAsync
](https://github.com/KeithHenry/chromeExtensionAsync)

**Comment by projectdelphai** [comment]
I'm not opposed to writing a chrome extension, but since I would need to do some sort of rewrite it could take some time. And in the context that the Firefox extension still has a lot of cleaning up and maintaining to do, I probably won't do it immediately. 

I'm not immediately free until Friday evening, so I'll probably work on maintenance/clean up stuff until then (and hopefully @photodiode responds by then). I'm hesitating to do too much since all the issues/pull requests are stored on this repo and I don't want to make a new one if photodiode could just transfer ownership.

Either way, I'll look at seeing how a chrome extension would work on the weekend and seeing if it's possible.

**Comment by Deledrius** [comment]
If you are planning to fork the project (I am hopeful _one_ of these forks will be maintained), it may be worth noting that there is another quiet fork that has additional features you may want incorporate: https://github.com/nyordanov/panorama (https://addons.mozilla.org/en-GB/firefox/addon/basic-panorama/)

**Comment by mikhoul** [comment]
@projectdelphai   I'm not really good at JS but I ported some extensions for my ow use so I know like I said that with the polyfill/library you should be able to write just one version of the extension since they share almost the same API. 

Take few minutes to read this page: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension  It explain very well how it work. 

The main difference is that Chrome don't support "promise" like Firefox so instead of rewriting the code specially for Chrome you load the polyfil;/library that will take care transparently of the conversion of the promise on the Chrome side.

Firefox supports both "chrome" and "browser" namespaces so it is easy, you should just use "chrome" namepsace unless it is a special API, it will save you to keep 2 different versions. of the extension 😉

Like I said for "Tab Managers" extension the main difference is the tab hiding API that Firefox have and Chrome don't have. The purpose of this API is to be able to hide tabs  but keeping them loaded.  

But the trend is more to "suspend" the tabs you don't plan to  use soon instead of keeping them alive in the background running.

Use this chart also for Browser support for JavaScript APIs:  https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs

Let me know about the progress and if I can help you in any way for testing or suggestions.

Maybe one day after following online course about JS I will have enough knowledge to be able to help you with the code. 

Wishing you a nice week-end :octocat:

**Comment by projectdelphai** [comment]
@Deledrius I saw that fork and I was looking at any changes they did that I didn't see in mine. I already implemented dragging a tab out of a group create a new group for it. I'll probably work on creating new groups with the mouse.

I'm not sure what else it has that I don't, but I'll make sure to keep an eye on it. I'm working on making a firefox add-on for it so other people can install it and adding some more documentation. I'll work on new features after I sort through any issues left over from the last repo.

**Comment by projectdelphai** [comment]
@mikhoul I know about the tab hiding and I was planning on just closing and opening tabs since Chrome doesn't allow for tab hiding. 

I didn't know about the Promise issue in Chrome but I get what you're saying. I probably won't get to it until later, but I'll make sure to keep it in mind :)

**Comment by Deledrius** [comment]
Unfortunately, any tab groups addon which closes and reopens or reloads a tab is a deal-breaker for me.  The action of changing which group a tab is in should never (by default) change the state of that tab's contents, and certainly not so destructively.

**Comment by projectdelphai** [comment]
@Deledrius What i'm talking about with @mikhoul is for a potential port to a Chrome add-on. And unfortunately Chrome doesn't support tab hiding so to emulate the same functionality, there's no other option than to close and open the tabs (as far as I can see at least). I don't like it either, but then again I'm using Firefox so it doesn't matter. What a chrome add-on would be doing is emulating the behavior as close as we can until tab-hiding is implemented (if ever).

The Firefox add-on won't change though.

**Comment by Deledrius** [comment]
Glad to hear it.  :)  I wasn't sure from the wording whether you meant to propagate that limitation to Firefox as well for simplicity.
